apiVersion: v1
kind: Service
metadata:
  name: chess-reporter-jupyter-lab
  namespace: chess-reporter
spec:
  type: NodePort
  selector:
    app: chess-reporter-jupyter-lab
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-reporter-jupyter-lab
  namespace: chess-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-reporter-jupyter-lab
  template:
    metadata:
      labels:
        app: chess-reporter-jupyter-lab
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: chess-reporter-jupyter-lab
          image: ghcr.io/nielsencampos/chess-reporter-jupyter-lab:latest
          ports:
            - containerPort: 8888

          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
