apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chess-reporter-data
  namespace: chess-reporter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-reporter
  namespace: chess-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-reporter
  template:
    metadata:
      labels:
        app: chess-reporter
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: chess-reporter
          image: ghcr.io/nielsencampos/chess-reporter:latest
          env:
            - name: CHESS_ENGINE_HOST
              value: "chess-engine"
            - name: CHESS_ENGINE_PORT
              value: "8080"
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "8000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: chess-reporter-data
