apiVersion: v1
kind: Service
metadata:
  name: chess-reporter
  namespace: chess-reporter
spec:
  type: NodePort
  selector:
    app: chess-reporter
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-reporter
  namespace: chess-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-reporter
  template:
    metadata:
      labels:
        app: chess-reporter
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: chess-reporter
          image: ghcr.io/nielsencampos/chess-reporter:latest
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: notebooks
              mountPath: /app/notebooks
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "16Gi"
              cpu: "8000m"
      volumes:
        - name: data
          hostPath:
            path: ${LOCAL_PATH}/data
            type: DirectoryOrCreate
        - name: notebooks
          hostPath:
            path: ${LOCAL_PATH}/notebooks
            type: DirectoryOrCreate
