apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-engine
  namespace: chess-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-engine
  template:
    metadata:
      labels:
        app: chess-engine
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: chess-engine
          image: ghcr.io/nielsencampos/chess-engine:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: chess-engine
  namespace: chess-reporter
spec:
  selector:
    app: chess-engine
  ports:
    - port: 8080
      targetPort: 8080
